### ISSUE TITLE
Add SmallDict?

### ISSUE THREAD

**Issue by jw3126** [matthias314/SmallCollections.jl#2]
Would a small dict type be in scope of this package? I am thinking of something like:
```julia
struct SmallDict{N,K,V} <: AbstractDict{K,V}
    pairs::SmallVector{N, Pair{K,V}}
    # or perhaps separate keys and vals vectors?
end
```

**Comment by matthias314** [comment]
That might be interesting. I've created a branch "smalldict" to try things out. You can install it via
```
pkg> add https://github.com/matthias314/SmallCollections.jl#smalldict
```
in Julia's package manager. It has an immutable dictionary `SmallDict` as well as `MutableSmallDict` (based on `MutableSmallVector` that I've been working on). Check out the short docstrings. Both creation and access seem to be faster than for `Dict`. At present, `SmallDict` with `unique = false` allocates; I don't fully understand why.

**Comment by jw3126** [comment]
> At present, `SmallDict` with `unique = false` allocates; I don't fully understand why.

I also don't fully understand why. My vague mental model is if mutable structs are involved compiler heuristics are fragile and often you get allocs.

**Comment by jw3126** [comment]
This removed the alloc for me:
```julia
function SmallDict{N,K,V}(itr; unique = false)::SmallDict{N,K,V} where {N,K,V}
    if unique
        SmallDict(SmallVector{N,Pair{K,V}}(itr))
    else
        d = SmallDict{N,K,V}()
        for (k,v) in itr
            d = push(d, k=>v)
        end
        d
    end
end

```

**Comment by matthias314** [comment]
> This removed the alloc for me

That's true. However, the goal was to use the much faster `push!` for `MutableSmallVector`.

**Comment by matthias314** [comment]
For `SmallDict` with `unique = false` I don't know a better way than what you have suggested, at least for dictionaries with not too many (32?) elements. It's in the "smalldict" branch now. I've also changed the implementation so that keys and values are now in separate vectors. This makes loop-ups (with small key types) faster. If you have any feedback, please let me know.
